# Spring配置
spring:
  application:
    name: "single"
    project: "bitactor-example"
  # bitactor框架配置
  bitactor:
    # 网关服务（gateway）对外暴露配置
    connector:
      # 对外暴露的端口,配置该值后将开启网关服
      port: 8877
      # TCP WS KCP
      net-protocol: TCP
      big-endian: true
      msg-receive-event-loop-open: true
      msg-event-loop-name-prefix: "消息分发"
      msg-event-loop-threads: 5

